version: '3.9'

services:
  db:
    image: postgres:16
    container_name: task_api_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_api
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d task_api"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: task_api_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
     
      DATABASE_URL: postgres://postgres:postgres@db:5432/task_api
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data:
