name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: task_api
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d task_api"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/task_api
      JWT_SECRET: ci-secret
      JWT_EXPIRES_IN: 15m
      REFRESH_EXPIRES_IN: 7d

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Wait for Postgres health
        run: |
          for i in {1..60}; do
            nc -z localhost 5432 && echo "Postgres up" && break
            echo "Waiting Postgres..."
            sleep 1
          done

      - name: Run migrations
        run: npm run db:migrate:up

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
